### ISSUE TITLE
Revisar PR abertos

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-bot#257]
#### Atualização da descrição dos PRs: 
- [x] #204
- [x] #199 
- [x] #196

#### Análise e Refatoração para cada um dos PRs
- [x] #204
- [x] #199
- [x] #196

#### Outros
- [x] Deploy e Testes em staging

## Definição de entregue:
- [ ] Atualização da imagem do serviço em produção
- [ ] Atualização das configurações do container para verficar no endpoint criado

**Comment by rolivegab** [comment]
Acredito que o PR #199 já tenha sido resolvido, falta alguém validar e submeter, vou continuar com os outros.
