### ISSUE TITLE
MDM não envia requisição pois variável de ambiente no client aponta para chatbot

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-bot#306]

**Comment by igr-santos** [comment]
Fazendo alguns testes na aplicação localmente, com intuito de verificar o fluxo de envio de mensagem em massa, o seguinte problema ocorreu, ao tentar buscar os ativistas pelas campanhas, eu recebo um timeout na requisição, mas isso não acontece se no mesmo ambiente, eu executo a query no console da API-GraphQL.
