### ISSUE TITLE
[beta] Não responde a mensagens padrão de erro, e aparentemente não envia texto livre para inteligência artificial (WiT)

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde-bot#315]
- Testar com versão BETA em produção https://www.facebook.com/beta.feminista/

**Comment by igr-santos** [comment]
**Solicitante:** Maíra (Nossas)

- Após um semana de depuração entre as aplicações no ambiente de staging e produção, pude concluir que algo está fazendo as funções da API-v2 relacionados a interação do usuário estourar o tempo limite da requisição.
- O webserver BETA não está preparado para receber um erro de timeout, pois esse problema não deveria acontecer em produção, da mesma maneira que não acontece em staging.
- O problema ocorria quando tentava parsear um erro que é esperado como objeto, porém no caso do timeout esse erro é texto (ainda não temos um padrão bem definidos sobre erro, mas deve-se levar em consideração a camada em que os erros podem acontecer)
- Para resolver parcialmente o problema acima, um tratamento de erro foi adicionado para que o fluxo continue até o final, ignorando o fato de que algum problema aconteceu no momento em que salvamos a interação do usuário.

** Agora é importante entender o porque API-v2 retorna um timeout nas requisições em produção, pois é nesse momento das interações entre Facebook -> Webserver -> API que devemos focar a correção oficial.

**Comment by lpirola** [comment]
problemas de performance resolvido com upgrade das instâncias do banco
