### ISSUE TITLE
Queue to process the mass message sending

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde-bot#48]
# Description
É necessário que o processamento de envio de mensagem em massa seja manipulada através de uma fila, para garantir a entrega da mensagem aos seus destinatários, caso ocorra algo de inesperado no processo de envio. A ideia é implementar uma fila usando redis com a lib [bull](https://github.com/OptimalBits/bull).

**Comment by gabrielrtakeda** [comment]
**Anotações**

>No momento de enviar a mensagem em massa, salvar na mesma tabela de interactions. Que tem hoje mensagem do usuário e `is_bot` (sugestão: `is_mass_message`).
>
>Também adicionar qual o usuário que enviou a mensagem em massa. Isso pode ser salvo na coluna `interaction` também. Já que é uma coluna JSONB.

**Comment by lpirola** [comment]
Fila de envio de mensagens em massa BETA

1. Receber parametros da busca
2. Buscar recipientId baseado nos parametros da busca
3. Efileirar mensagens
4. Criar o worker

**Comment by gabrielrtakeda** [comment]
- [ ] Receber informações de quick reply e formatar objeto para envio
